#! /bin/bash

# ======
# rst2nn
# ======
#
# :Author: Adrian Perez <moebius@connectical.net>
# :Copyright: Copyright (c) 2006 Connectical Labs.
# :Licensing: Distributed under terms of the MIT license.
# :Abstract: This shell script is a small convenience to convert
#    reStructuredText_ to LaTeX with the appropiate options to
#    typeset the output with the ``connectical`` LaTeX document
#    class.
#
# .. _reStructuredText: http://docutils.sf.net/rst.html

# Implementation
# ==============

output_file=""

rst2latex="rst2latex.py"

rst_options="--documentclass=scrartcl
	--documentoptions=11pt,a4paper,DIVcalc
	--table-style=booktabs
	--use-latex-citations
	--use-latex-footnotes
	--use-latex-docinfo
	--use-latex-toc"


set_document_class ()
{
	local exp='1s/scrartcl/connectical/'
	if [ "${output_file}" ] ; then
		sed -i -e "${exp}" "${output_file}"
	else
		sed -e "${exp}"
	fi
}


while [[ $1 = --* ]] ; do
	rst_options="${rst_options} $1"
	shift
done

if [ $# -eq 1 ] ; then
	# Act as a filter.
	${rst2latex} ${rst_options} "$1" | set_document_class
elif [ $# -eq 2 ] ; then
	output_file=$2
	${rst2latex} ${rst_options} "$1" "${output_file}"
	set_document_class
else
	echo "Bad command line" 1>&2
	exit 1
fi

